# Tests the local GitHub Action.
#
# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
---
name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        # k3s-channel: https://update.k3s.io/v1-release/channels
        include:
          - k3s-channel: latest
            test-pods: restarted healthy non-ready pending
            input-namespace: ""
            input-pod-selector: pod-number notin (2,3)
            input-important-workloads: pod/test-healthy-1 pod/test-healthy-2
          - k3s-channel: stable
            test-pods: ""
            input-namespace: kube-system
            input-important-workloads: ""

    steps:
      - uses: actions/checkout@v4

      # Start a local k8s cluster
      # https://github.com/jupyterhub/action-k3s-helm/
      - name: Setup k8s
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: ${{ matrix.k3s-channel }}
          metrics-enabled: false
          traefik-enabled: false


      # Prepare a set of pods with various conditions for testing of report
      - name: "Prepare test pods: restarted"
        if: contains(matrix.test-pods, 'restarted')
        run: |
          kubectl apply -f ci/restarted-pod.yaml

      - name: "Prepare test pods: healthy"
        if: contains(matrix.test-pods, 'healthy')
        run: |
          kubectl apply -f ci/healthy-pod.yaml

      - name: "Prepare test pods: non-ready"
        if: contains(matrix.test-pods, 'non-ready')
        run: |
          kubectl apply -f ci/non-ready-pod.yaml

      - name: "Prepare test pods: pending"
        if: contains(matrix.test-pods, 'pending')
        run: |
          kubectl apply -f ci/pending-pod.yaml

      - name: "Prepare test pods: wait 10 seconds"
        if: matrix.test-pods != ''
        run: |
          sleep 10


      # IMPORTANT: This step only only tests that the action doesn't error
      #            unexpectedly. Please rely on manual inspection of the report.
      - name: Kubernetes namespace report - Inspect me!
        uses: ./
        id: k8s-namespace-report
        with:
          namespace: ${{ matrix.input-namespace }}
          pod-selector: ${{ matrix.input-pod-selector }}
          important-workloads: ${{ matrix.input-important-workloads }}


      # - name: Validate local action's set outputs/envs
      #   run: |
      #     echo "my-output=${{ steps.k3s.outputs.my-output }}"
      #     echo "---"
      #     EXIT=0
      #     if [[ -z "${{ steps.k3s.outputs.my-output }}" ]]; then
      #         echo "my-output not set as an action output"
      #         EXIT=1
      #     fi
      #     exit $EXIT
